---
title: "fitness_analysis"
author: "julianascii"
output: html_document
---

```{r}
# load packages
library(dplyr)
library(readr)
library(ggplot2)
```

```{r}
# read file
fitness <- read_csv("fitness_dataset.csv")

# initial inspection
glimpse(fitness)
head(fitness)
summary(fitness)
```

```{r}
# average and median values of the program
avg_age <- mean(fitness$age)
avg_duration <- mean(fitness$duration_min)
avg_calories_burned <- mean(fitness$calories_burned)
avg_heart_rate <- mean(fitness$heart_rate_avg)
avg_steps <- mean(fitness$steps)
avg_sleep_hours <- mean(fitness$sleep_hours)
avg_weight <- mean(fitness$weight_kg)

median_age <- median(fitness$age)
median_duration <- median(fitness$duration_min)
median_calories_burned <- median(fitness$calories_burned)
median_heart_rate <- median(fitness$heart_rate_avg)
median_steps <- median(fitness$steps)
median_sleep_hours <- median(fitness$sleep_hours)
median_weight <- median(fitness$weight_kg)

# optional: print the values (for mean)
print(paste("The average age of participants joining the program is", format(avg_age, digits = 2)))
print(paste("The average duration (in minutes) undergone by participants joining the program is", format(avg_duration, digits = 2)))
print(paste("The average calories burned by the participants joining the program is", format(avg_calories_burned, digits = 3), "calories."))
print(paste("The average heart rate of the participants joining the program is", format(avg_heart_rate, digits = 3), "beats per minute."))
print(paste("The average number of steps acocmplished by the participants joining the program is", format(avg_steps, digits = 5), "steps."))
print(paste("The average sleeping hours of the participants joining the program is", avg_sleep_hours, "hours."))
print(paste("The average weight (in kilograms) of the participants joining the program is", avg_weight, "kilograms."))

# optional: print the values (for median)
print(paste("The median age of participants joining the program is", format(median_age, digits = 2)))
print(paste("The median duration (in minutes) undergone by participants joining the program is", format(median_duration, digits = 2)))
print(paste("The median calories burned by the participants joining the program is", format(median_calories_burned, digits = 3), "calories."))
print(paste("The median heart rate of the participants joining the program is", format(median_heart_rate, digits = 3), "beats per minute."))
print(paste("The median number of steps acocmplished by the participants joining the program is", format(median_steps, digits = 5), "steps."))
print(paste("The median sleeping hours of the participants joining the program is", median_sleep_hours, "hours."))
print(paste("The median weight (in kilograms) of the participants joining the program is", median_weight, "kilograms."))
```

```{r}
# further insights
gender_count <- fitness %>%
    group_by(gender) %>%
    summarize(count = n())
gender_count

age_1 <- fitness %>%
  group_by(age) %>%
  filter(age < 18) %>%
  summarize(count = n())
age_1

act_type <- fitness %>%
  group_by(activity_type) %>%
  summarize(count = n())
act_type
```

```{r}
# make vizualizations
viz1 <- ggplot(fitness, aes(x = duration_min,
                            y = calories_burned)) +
        geom_point(aes(color = weight_kg), 
                   alpha = 1) +  
        geom_smooth() +
        labs(
          title = "Duration of Workout VS Calories Burned",
          subtitle = "Considering Weight in Kilograms",
          x = "Duration of Workout", 
          y = "Calories Burned",
          color = "Weight (Kg)"
             ) +
        theme_minimal(base_size = 13) +
        theme(
          plot.title = element_text(face = "bold", size = 15),
          plot.subtitle = element_text(size = 13, color = "gray40")
             )
viz1

# for previous analyses
viz2 <- ggplot(fitness, aes(x = activity_type)) +
        geom_bar(color = "darkgreen",
                 width = 0.7,
                 fill = "pink"
                 ) +
        geom_text(
          stat = "count",
          aes(label = after_stat(count)),
          position = position_stack(vjust = 0.5),
          size = 3.5,
          color = "black"
                 ) +
        labs(
          title = "Activity Types",
          subtitle = "With the Number of Fitness Goers Involved",
          x = "Activity Type",
          y = "Frequency"
            ) +
        theme(
          plot.title = element_text(face = "bold", size = 15),
          plot.subtitle = element_text(size = 13, color = "gray40"),
          axis.text.x = element_text(size = 10)
        )
viz2
```